parameters:
  spotify_job_offers_url: http://localhost:8000
#  spotify_job_offers_url: https://www.spotifyjobs.com/wp-admin/admin-ajax.php
#  content-type:application/x-www-form-urlencoded; charset=UTF-8
#  action=get_jobs&pageNr=2&perPage=16&featuredJobs=&category=0&location=0&search=&locations%5B%5D=sweden
