version: '3'
services:
    php:
        build:
            context: .
            dockerfile: 'dockerfile'
        env_file:
            - docker-compose.env
        environment:
            SSH_AUTH_SOCK: /tmp/ssh-agent.sock
        volumes:
            - ./:/var/www/app/
            - ${SSH_AUTH_SOCK}:/tmp/ssh-agent.sock
        working_dir: /var/www/app/
        hostname: php-serv
